name: Build and Deploy Docker Image for Strapi345

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t strapi:latest .
          docker save strapi:latest -o strapi.tar

      - name: Upload Docker image to GitHub artifacts
        uses: actions/upload-artifact@v2
        with:
          name: strapi-image
          path: strapi.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Docker image from GitHub artifacts
        uses: actions/download-artifact@v2
        with:
          name: strapi-image
          path: .

      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          source: "strapi.tar"
          target: "/root/docker_images/"
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /root/docker_images
            docker load -i strapi.tar
            docker stop strapi || true
            docker rm strapi || true
            docker run -d -p 3005:1337 --name strapi \
              -e APP_KEYS='${{ secrets.APP_KEYS }}' \
              -e API_TOKEN_SALT='${{ secrets.API_TOKEN_SALT }}' \
              -e ADMIN_JWT_SECRET='${{ secrets.ADMIN_JWT_SECRET }}' \
              -e TRANSFER_TOKEN_SALT='${{ secrets.TRANSFER_TOKEN_SALT }}' \
              -e DATABASE_CLIENT='postgres' \
              -e DATABASE_HOST='94.198.216.72' \
              -e DATABASE_PORT='5432' \
              -e DATABASE_NAME='strapi' \
              -e DATABASE_USERNAME='strapi_user' \
              -e DATABASE_PASSWORD='EOpe$wsxdp+wnby' \
              -e DATABASE_SSL='false' \
              -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
              -v strapi-public:/srv/app/public \
              strapi:latest
            docker logs strapi
          debug: true

      - name: Clean up Docker
        run: |
          docker system prune -a -f